18:49:29 - INFO - Memory changes during cleanup:
18:49:29 - INFO - D:\Anaconda\Lib\tracemalloc.py:115: size=0 B (-80.6 KiB), count=0 (-1032)
18:49:29 - INFO - D:\Anaconda\Lib\ctypes\__init__.py:64: size=62.6 KiB (+62.6 KiB), count=2 (+2), average=31.3 KiB
18:49:29 - INFO - D:\Anaconda\Lib\tracemalloc.py:193: size=0 B (-46.6 KiB), count=0 (-995)
